version: '3.7'

services:
  ## Database
  mysql-db:
    image: mysql:5.7.29
    restart: on-failure
    container_name: mysql-database
    environment:
      - MYSQL_ROOT_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - petclinic-network
    ports:
      - 3306:3306

  config-server:
    image: springcommunity/spring-petclinic-config-server
    container_name: config-server
    volumes:
      - ./configuration:/config
    environment:
      - GIT_REPO=config
    networks:
      - petclinic-network
    ports:
      - 8888:8888
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access


  discovery-server:
    image: springcommunity/spring-petclinic-discovery-server
    container_name: discovery-server
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 8761:8761
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  customers-service:
    image: springcommunity/spring-petclinic-customers-service
    container_name: customers-service
    depends_on:
      - mysql-db
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 8081:8081
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access


  visits-service:
    image: springcommunity/spring-petclinic-visits-service
    container_name: visits-service
    depends_on:
      - mysql-db
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 8082:8082
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access


  vets-service:
    image: springcommunity/spring-petclinic-vets-service
    container_name: vets-service
    depends_on:
      - mysql-db
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 8083:8083
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access


  api-gateway:
    image: springcommunity/spring-petclinic-api-gateway
    container_name: api-gateway
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 8080:8080
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  tracing-server:
    image: openzipkin/zipkin
    container_name: tracing-server
    environment:
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
    networks:
      - petclinic-network
    ports:
      - 9411:9411
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  admin-server:
    image: springcommunity/spring-petclinic-admin-server
    container_name: admin-server
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "-XX:+UnlockExperimentalVMOptions", "-XX:+UseCGroupMemoryLimitForHeap", "-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]
    networks:
      - petclinic-network
    ports:
      - 9090:9090
    logging:
      driver: fluentd
      options:
        fluentd-address: localhost:24224
        tag: httpd.access

  # metrics visualisation
  grafana-server:
    build: ./docker/grafana
    container_name: grafana-server
    networks:
      - petclinic-network
    ports:
      - 3000:3000

  # metrics scrapping
  prometheus-server:
    build: ./docker/prometheus
    container_name: prometheus-server
    networks:
      - petclinic-network
    ports:
      - 9091:9090

  ## Logs scraping
  fluentd:
    build:
      context: docker/fluentd
      dockerfile: Dockerfile
    networks:
      - petclinic-network
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    networks:
      - petclinic-network
    expose:
      - 9200
    ports:
      - 9200:9200

  # Logs visualisation
  kibana:
    image: kibana:7.6.0
    networks:
      - petclinic-network
    ports:
      - 5601:5601

volumes:
  elasticsearch_data:

networks:
  petclinic-network:
    driver: bridge
